### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.collective'

### ISSUE THREAD

**Issue by cissoidx** [hongluzhou/composer#1]
Hello Honglu Zhou,

As described in the title, this file/class/method is not found.
Can you please update the missing file?

cheers,

**Comment by cissoidx** [comment]
Hello @hongluzhou ,
Can you please make sure if all the files are uploaded?

cheers

**Comment by hongluzhou** [comment]
Thank you very much for your interests! The code was uploaded. Closing the issue now. 

Best,
Honglu
