### ISSUE TITLE
Cannot find the checkpoint link

### ISSUE THREAD

**Issue by JinZhangYu** [hongluzhou/composer#12]
I try to find the model checkpoint at https://drive.google.com/file/d/1rBQSoGS7MrhvDaPRtVi0TbZygoe63Fo_/view?usp=sharing

But it turns out that 'Pages Not Found'.

I cannot appreciate it more if you could update the link. Thanks.

**Comment by hongluzhou** [comment]
Sorry about that! There has been some file migration. Please download the checkpoints using https://drive.google.com/file/d/1mtxdGH9ae8nCnbD3RPCoGw9_hsmNqVn6/view?usp=sharing

**Comment by shutu-1** [comment]
I tried to find the Volleyball data folder and the Collective Activity data folder using the provided links, 
but it seems that the pages are not found. 
I would greatly appreciate it if you could update the links. Thanks.

**Comment by hongluzhou** [comment]
The links on the README page were updated. Please check. Thanks.
