### ISSUE TITLE
The sinkhorn algorithm

### ISSUE THREAD

**Issue by cissoidx** [hongluzhou/composer#4]
Hello @hongluzhou ,

In the paper, online clustering secion, you mentioned to enforce equipartion, the vector are set to ones. As far as I understand, the sinkhorn algorithm is to find optimal transport between two distributions given a cost matrix.

My questions:
1. why equipartition is done?
2. Is there a cost matrix here? if yes, which one?

Can you please help?

cheers,
xu

**Comment by hongluzhou** [comment]
Equipartition prevents the trivial solution where every clip has the same code. For more information regarding this (or the Sinkhorn-Knopp algorithm), please refer to:

- https://github.com/facebookresearch/swav (our code on this part uses their implementation)
- https://m0nads.wordpress.com/tag/sinkhorn-knopp-algorithm/
- https://theaisummer.com/swav/
- https://youtu.be/M_DgS3XGeJc
- https://youtu.be/uqJ2hbDGHjY 
- https://youtu.be/7QmsTleiRLs 
- https://youtu.be/jCg97EAVsy8
- https://wandb.ai/authors/swav-tf/reports/Unsupervised-Visual-Representation-Learning-with-SwAV--VmlldzoyMjg3Mzg
