### ISSUE TITLE
Q about ablations in paper

### ISSUE THREAD

**Issue by ajtao** [hongluzhou/composer#6]
Hello, congrats on the amazing work!

For Table 2 of the Supplementary material, it shows that 1-scale keypoint model achieved 91.2 test accuracy.
I was wondering if you can say a little bit about what portion of the model this was. Was this a model that only used the first transformer layer "inner" and not the other 3 transformer layers (middle, outer, group)?

**Comment by hongluzhou** [comment]
Thank you! ☺️  Sorry about my late reply! Yes, this ablation variant only used the first transformer layer "inner". Please see Eq. (6) and Eq. (7) in the supplementary material for the exact formulation:
<img width="649" alt="1 scale" src="https://user-images.githubusercontent.com/32147325/205767907-559f6d9d-ec30-4a90-b798-6bd9bb3c7f23.png">
Feel free to let me know if you have any follow-up questions!

Best,
Honglu
