### ISSUE TITLE
volleyball.zip can't download

### ISSUE THREAD

**Issue by kimsjpk1** [hongluzhou/composer#9]
i hope to download volleyball dataset(joint pickle files)

i did download volleyball dataset about 3 month ago but i can't download volleyball dataset now

please check your upload files and upload fixed file.

i can download CAD dataset.

thank you

**Comment by hongluzhou** [comment]
> i hope to download volleyball dataset(joint pickle files)
> 
> i did download volleyball dataset about 3 month ago but i can't download volleyball dataset now
> 
> please check your upload files and upload fixed file.
> 
> i can download CAD dataset.
> 
> thank you

Thank you for your interest! The link to downloading the volleyball.zip seems to be fine. Could you try again? Perhaps VPN is required. https://drive.google.com/file/d/1NF7aiplia3g5Ng5pARoYjS47wPz66XCx/view

Best,
Honglu

**Comment by hongluzhou** [comment]
Using the above link, I was able to download the file yesterday. Therefore, closing this issue now. Please feel free to contact me again if you need further assistance.
